#### Pandas Csv
- csv is a comma separated values
- differance b/w csv and excel
    1. both are using store the large amount of data like lakhs of records or gb,tb,pb
    2. both are row and column based files
    3. csv files occupies less memory when compare to excell

In [1]:
import pandas as pd
info = pd.read_csv('student_info.csv')
info

,S.No,First Name,Middle Name,Last Name,Email,Contact,Address,Gender,section
0,1,Venkat,Chowdary,Yekkanti,venkat@gmail.com,98765432,hyerabad,Male,ECE
1,2,sekhar,Chowdary,nallapati,selhar@gmail.com,4567876,hyerabad,Male,CSE
2,3,Krishna,Prasad,Kate,kp@gmail.com,67897657,banglore,Male,ECE
3,4,Divya,Chowdary,Abcd,divya@gmail.com,987654678,Chennai,Female,ECE
4,5,Venkat,Chowdary,Yekkanti,venkat@gmail.com,98765432,hyerabad,Male,ECE
5,6,sekhar,Chowdary,nallapati,selhar@gmail.com,4567876,hyerabad,Male,CSE
6,7,Krishna,Prasad,Kate,kp@gmail.com,67897657,banglore,Male,ECE
7,8,Divya,Chowdary,Abcd,divya@gmail.com,987654678,Chennai,Female,ECE

In [3]:
print(info.to_string())

   S.No First Name Middle Name  Last Name             Email    Contact   Address  Gender section
0     1     Venkat    Chowdary   Yekkanti  venkat@gmail.com   98765432  hyerabad    Male     ECE
1     2     sekhar    Chowdary  nallapati  selhar@gmail.com    4567876  hyerabad    Male     CSE
2     3    Krishna      Prasad       Kate      kp@gmail.com   67897657  banglore    Male     ECE
3     4      Divya    Chowdary       Abcd   divya@gmail.com  987654678   Chennai  Female     ECE
4     5     Venkat    Chowdary   Yekkanti  venkat@gmail.com   98765432  hyerabad    Male     ECE
5     6     sekhar    Chowdary  nallapati  selhar@gmail.com    4567876  hyerabad    Male     CSE
6     7    Krishna      Prasad       Kate      kp@gmail.com   67897657  banglore    Male     ECE
7     8      Divya    Chowdary       Abcd   divya@gmail.com  987654678   Chennai  Female     ECE

In [4]:
output=pd.read_csv('info_data.csv')
output

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [5]:
# head function read top 5 records
# tail function read bottom 5 records
output.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [6]:
output.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [7]:
output.head(20)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0

In [12]:
# now we will do data analysis
# 1. how many records for duration 60
df1 = output[output['Duration']==60]
df2 = df1[df1['Pulse']==110]
df2

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
6          60    110       136     374.0
149        60    110       150     409.4
165        60    110       145     300.0

In [20]:
test1 = output[['Pulse','Calories','Duration','Maxpulse']]
print(test1.head())
print(output.head())

   Pulse  Calories  Duration  Maxpulse
0    110     409.1        60       130
1    117     479.0        60       145
2    103     340.0        60       135
3    109     282.4        45       175
4    117     406.0        45       148
   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0